server:
  port: 8081
  # 需要设置web服务器的关闭方式，默认是立即关闭，需要修改为优雅关闭
  shutdown: graceful
#暴漏所有断点（默认只暴漏health和info）如果想指定具体的端点，可以使用,进行分割（如：health,info,beans）
management:
  endpoints:
    web:
      exposure:
        include: "*"
      #  路径信息，默认为actuator
      base-path: /qudehu
      #  默认就是开启的
    enabled-by-default: true
  #    显示所有的健康状态
  endpoint:
    health:
      show-details: always

# 配置数据源方便查看数据库连接状态
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/swtest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        #指定服务端地址
        url: http://localhost:8082
        username: qudehu
        password: qudehu

# 配置日志信息，方便后续查看日志信息
logging:
  file:
    name: D:/logs/application.log

info:
  appName: spring-boot-admin
  version: 1.0.0
  description: spring-boot-admin-server
#  通过maven的数据进行展示
  mavenAppName: @project.artifactId@
  mavenAppVersion: @project.version@
